### ISSUE TITLE
As an Alumni, I want to update my skills on my profile

### ISSUE THREAD

**Issue by Seyha-Soeurn** [pnc-virtual-company/2022-G3-VC2-PART2#25]

**Comment by Phearun-chhun** [comment]
![Image](https://user-images.githubusercontent.com/90229357/190307509-ec7bfdf1-5917-4026-b90b-b8664b346368.png)
![Image](https://user-images.githubusercontent.com/90229357/190307508-fbc3b350-1209-4b91-b950-02b8ffe5293a.png)
