### ISSUE TITLE
As an admin, I want to create a ERO account

### ISSUE THREAD

**Issue by Seyha-Soeurn** [pnc-virtual-company/2022-G3-VC2-PART2#48]

**Comment by Phearun-chhun** [comment]
![Image](https://user-images.githubusercontent.com/90229357/190939292-864a125e-ff02-4554-b170-8b628f6fe4e7.png)



![Image](https://user-images.githubusercontent.com/90229357/190939297-7a3af58e-e9b8-4dc0-a3af-c70fc573882a.png)
