### ISSUE TITLE
As an Alumni, I want to update my general information on my profile

### ISSUE THREAD

**Issue by Seyha-Soeurn** [pnc-virtual-company/2022-G3-VC2-PART2#6]

**Comment by Phearun-chhun** [comment]
![Image](https://user-images.githubusercontent.com/90229357/189472957-b0d58da4-1038-4069-8a00-10564af6c980.png)
![Image](https://user-images.githubusercontent.com/90229357/189472959-914488e5-8a4d-4a09-9f11-2d1067cae065.png)
![Image](https://user-images.githubusercontent.com/90229357/189472960-3fda22ac-7c9d-4e93-bf9b-250900d94a6a.png)

**Comment by Phearun-chhun** [comment]
This feature covers the following user stories
✓As alumni, I want to edit my general information so that I can keep informed about the school.
